from fastapi import FastAPI, Depends, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from sqlalchemy.orm import Session
from typing import List

from app.core.database import engine, Base, get_db
from app.models.interaction import HCPInteraction
from app.schemas.interaction import InteractionCreate, InteractionResponse, ChatRequest
from app.core.agent import agent_executor

# Ensure database tables match current model definitions on startup
Base.metadata.create_all(bind=engine)

app = FastAPI(title="AI-First CRM HCP Module")

# ------------------------------------------------------------------
# CORE SECURITY MIDDLEWARE (CORS DEFINITION)
# ------------------------------------------------------------------
# Explicitly whitelist standard frontend development origins and methods
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins (localhost:5173, localhost:5174, etc.)
    allow_credentials=True,
    allow_methods=["*"],  # Allows GET, POST, OPTIONS, PUT, DELETE
    allow_headers=["*"],  # Allows all headers
)

# ------------------------------------------------------------------
# API ENDPOINTS
# ------------------------------------------------------------------

# Endpoint 1: Structured Form submission
@app.post("/api/interactions", response_model=InteractionResponse)
def create_interaction(data: InteractionCreate, db: Session = Depends(get_db)):
    db_interaction = HCPInteraction(
        hcp_name=data.hcp_name,
        discussion_topic=data.discussion_topic,
        summary=data.summary,
        next_steps=data.next_steps
    )
    db.add(db_interaction)
    db.commit()
    db.refresh(db_interaction)
    return db_interaction

# Endpoint 2: Get all interactions (useful to populate a history view on your frontend)
@app.get("/api/interactions", response_model=List[InteractionResponse])
def get_interactions(db: Session = Depends(get_db)):
    return db.query(HCPInteraction).order_by(HCPInteraction.id.desc()).all()

# Endpoint 3: Conversational AI Agent Chat Interface
@app.post("/api/chat")
async def chat_with_agent(request: ChatRequest):
    try:
        # Run the string prompt directly through the LangGraph agent
        response = agent_executor.invoke({"messages": [("user", request.message)]})
        # Extract the final answer generated by the agent after evaluating the tools
        final_msg = response["messages"][-1].content
        return {"response": final_msg}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ------------------------------------------------------------------
# GLOBAL EXCEPTION CATCH (CORS SAFEGUARD ON CRASHES)
# ------------------------------------------------------------------
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """
    Catches 500 runtime errors and force-injects CORS headers.
    This stops the browser from displaying a confusing "CORS Blocked" error
    when the real issue is a backend database or model syntax error.
    """
    response = JSONResponse(
        status_code=500,
        content={"detail": f"Internal Server Crash: {str(exc)}"}
    )
    # Inject fallback header controls manually
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Credentials"] = "true"
    return response